version: "3"

services:
  api:
    container_name: api-service
    build: .
    restart: on-failure
    volumes:
     - ./:/webapps
      - ./log/:/var/log/apps
    ports:
      - 5002:5002
    env_file:
      - .env

    command: supervisord -n -c /etc/supervisor/supervisord.conf